line-length = 100

[lint.per-file-ignores]
  # init modules can contain the local imports, logic, unused imports
"__init__.py" = ["F401"]

[lint]
preview = true
select = ["E", "F", "I", "C90"]

[lint.flake8-quotes]
inline-quotes = "single"

[lint.pylint]
max-args = 6

[format]
quote-style = "single"
