line-length = 80

[lint]
preview = true
select = ["ALL"]
ignore = [
    "D211",
    "D213",
    "RUF002",
    "RUF003",
    "CPY001",
]

[lint.flake8-quotes]
inline-quotes = "single"

[lint.pylint]
max-args = 6

[format]
quote-style = "single"
